### ISSUE TITLE
Relax `directory` dependency lower limit

### ISSUE THREAD

**Issue by fosskers** [JustusAdam/elm-init#5]
Even Stackage's current `nightly` resolver only has up to `directory-1.2.2.0`.

**Comment by JustusAdam** [comment]
I know. But I am using the `withCurrentDirectory` Function which was introduced in 1.2.3.

**Comment by fosskers** [comment]
Consider using `shelly` :+1: I use it for all of my command-line programs, and it has lots of file/directory convenience functions.

**Comment by JustusAdam** [comment]
Thanks for the tip. I'll keep it in mind for the future.
